// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counties.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCounty = `-- name: CreateCounty :one
INSERT INTO counties (id, name, code, former_province, area_sq_km)
VALUES ( $1, $2, $3, $4, $5)
RETURNING id, name, code, former_province, area_sq_km, created_at
`

type CreateCountyParams struct {
	ID             int32          `json:"id"`
	Name           string         `json:"name"`
	Code           string         `json:"code"`
	FormerProvince pgtype.Text    `json:"former_province"`
	AreaSqKm       pgtype.Numeric `json:"area_sq_km"`
}

func (q *Queries) CreateCounty(ctx context.Context, arg CreateCountyParams) (County, error) {
	row := q.db.QueryRow(ctx, createCounty,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.FormerProvince,
		arg.AreaSqKm,
	)
	var i County
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.FormerProvince,
		&i.AreaSqKm,
		&i.CreatedAt,
	)
	return i, err
}

const getCounty = `-- name: GetCounty :one
SELECT id, name, code, former_province, area_sq_km, created_at FROM counties
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCounty(ctx context.Context, id int32) (County, error) {
	row := q.db.QueryRow(ctx, getCounty, id)
	var i County
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.FormerProvince,
		&i.AreaSqKm,
		&i.CreatedAt,
	)
	return i, err
}

const listCounties = `-- name: ListCounties :many
SELECT id, name, code, former_province, area_sq_km, created_at FROM counties
ORDER BY id
`

func (q *Queries) ListCounties(ctx context.Context) ([]County, error) {
	rows, err := q.db.Query(ctx, listCounties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []County{}
	for rows.Next() {
		var i County
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.FormerProvince,
			&i.AreaSqKm,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
