// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: indicators.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIndicator = `-- name: CreateIndicator :one
INSERT INTO indicators (code, name, description, unit, source)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, name, description, unit, source, created_at
`

type CreateIndicatorParams struct {
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Unit        string      `json:"unit"`
	Source      string      `json:"source"`
}

func (q *Queries) CreateIndicator(ctx context.Context, arg CreateIndicatorParams) (Indicator, error) {
	row := q.db.QueryRow(ctx, createIndicator,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.Source,
	)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getIndicatorByCode = `-- name: GetIndicatorByCode :one
SELECT id, code, name, description, unit, source, created_at FROM indicators
WHERE code = $1
LIMIT 1
`

func (q *Queries) GetIndicatorByCode(ctx context.Context, code string) (Indicator, error) {
	row := q.db.QueryRow(ctx, getIndicatorByCode, code)
	var i Indicator
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const listIndicators = `-- name: ListIndicators :many
SELECT id, code, name, description, unit, source, created_at FROM indicators
ORDER BY name
`

func (q *Queries) ListIndicators(ctx context.Context) ([]Indicator, error) {
	rows, err := q.db.Query(ctx, listIndicators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Indicator{}
	for rows.Next() {
		var i Indicator
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Unit,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
