// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type County struct {
	ID             int32              `json:"id"`
	Name           string             `json:"name"`
	Code           string             `json:"code"`
	FormerProvince pgtype.Text        `json:"former_province"`
	AreaSqKm       pgtype.Numeric     `json:"area_sq_km"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Indicator struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Unit        string             `json:"unit"`
	Source      string             `json:"source"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Observation struct {
	ID             pgtype.UUID        `json:"id"`
	CountyID       int32              `json:"county_id"`
	IndicatorID    pgtype.UUID        `json:"indicator_id"`
	Year           int32              `json:"year"`
	Value          pgtype.Numeric     `json:"value"`
	SourceDocument pgtype.Text        `json:"source_document"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
